version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./api.Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: qa
    ports:
      - "8080:8080"
    networks:
      - tpm-network
    depends_on:
      - db
      - cache
      - logstash

  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: ./ui.Dockerfile
    ports:
      - "80:80"
    networks:
      - tpm-network

  auth-server:
    container_name: auth-server
    build:
      context: ./auth-server
      dockerfile: ./auth-server.Dockerfile
    ports:
      - "8081:8080"
      - "8082:8443"
    networks:
      - tpm-network
    depends_on:
      - db
      - logstash

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: ./db.Dockerfile
    ports:
      - "5432:5432"
    networks:
      - tpm-network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  cache:
    container_name: cache
    build:
      context: ./cache
      dockerfile: ./cache.Dockerfile
    ports:
      - "6379:6379"
    networks:
      - tpm-network
    volumes:
      - cache-data:/data

  file-storage:
    container_name: file-storage
    build:
      context: ./file-storage
      dockerfile: ./file-storage.Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - tpm-network
    volumes:
      - ./file-storage/entrypoint.sh:/entrypoint.sh:ro,Z
      - file-storage-data:/data

  # Logging and monitoring services

  monitoring-setup:
    container_name: monitoring-setup
    build:
      context: ./monitoring/setup
      dockerfile: ./setup.Dockerfile
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./monitoring/setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./monitoring/setup/lib.sh:/lib.sh:ro,Z
      - ./monitoring/setup/roles:/roles:ro,Z
      - monitoring-setup-data:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - tpm-network
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./monitoring/elasticsearch
      dockerfile: ./elasticsearch.Dockerfile
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./monitoring/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch-data:/usr/share/elasticsearch/data:Z
    expose:
      - "9200"
      - "9300"
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - tpm-network
    restart: unless-stopped

  logstash:
    container_name: logstash
    build:
      context: ./monitoring/logstash
      dockerfile: ./logstash.Dockerfile
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./monitoring/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./monitoring/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - tpm-network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    container_name: kibana
    build:
      context: ./monitoring/kibana
      dockerfile: ./kibana.Dockerfile
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./monitoring/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - tpm-network
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  db-data:
  cache-data:
  file-storage-data:
  monitoring-setup-data:
  elasticsearch-data:

networks:
  tpm-network:
    driver: bridge
